OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
    Users:
      Count: 1
    # Enable TLS cert generation
    Template:
      Count: 1
    TLS:
      Enabled: true

PeerOrgs:
  - Name: Org1
    Domain: example.com
    Peers:
      - Hostname: peer0
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    TLS:
      Enabled: true
